export const shopCategories = [
    { value: "fashion", label: "Fashion & Apparel" },
    { value: "electronics", label: "Electronics & Tech" },
    { value: "home_garden", label: "Home & Garden" },
    { value: "beauty", label: "Beauty & Personal Care" },
    { value: "health", label: "Health & Wellness" },
    { value: "food_beverage", label: "Food & Beverage" },
    { value: "toys_games", label: "Toys & Games" },
    { value: "sports_outdoors", label: "Sports & Outdoors" },
    { value: "books_stationery", label: "Books & Stationery" },
    { value: "jewelry", label: "Jewelry & Accessories" },
    { value: "automotive", label: "Automotive" },
    { value: "pet_supplies", label: "Pet Supplies" },
    { value: "art_crafts", label: "Arts, Crafts & DIY" },
    { value: "baby_kids", label: "Baby & Kids" },
    { value: "furniture", label: "Furniture" },
    { value: "office_supplies", label: "Office Supplies" },
    { value: "musical_instruments", label: "Musical Instruments" },
    { value: "vintage_antiques", label: "Vintage & Antiques" },
    { value: "digital_goods", label: "Digital Goods" },
    { value: "handmade", label: "Handmade Items" },
    { value: "gifts", label: "Gifts & Occasions" },
    { value: "specialty_foods", label: "Specialty Foods" },
    { value: "collectibles", label: "Collectibles" },
    { value: "travel_accessories", label: "Travel Accessories" },
    { value: "sustainable_eco", label: "Sustainable & Eco-friendly" },
    { value: "party_supplies", label: "Party Supplies" },
    { value: "luggage", label: "Luggage & Bags" },
    { value: "watches", label: "Watches & Accessories" },
    { value: "organic", label: "Organic Products" },
    { value: "tools_hardware", label: "Tools & Hardware" },
    { value: "subscription_box", label: "Subscription Boxes" },
    { value: "footwear", label: "Footwear" },
    { value: "lingerie", label: "Lingerie & Sleepwear" },
    { value: "photography", label: "Photography" },
    { value: "prints_posters", label: "Prints & Posters" },
    { value: "other", label: "Other" }
  ];
